name: NodeJS with Grunt

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libappindicator3-dev libindicator3-dev
    # Ensure all dependencies are updated to address vulnerabilities and compatibility
    - name: Install and update dependencies
      run: |
        cd src
        npm install -g npm-check-updates
        ncu -u
        npm install
    - name: Build
      run: |
        cd src
        npm install
        grunt
